name: 'Terraform Plan'
description: 'Terraform init, validate, format check and plan'
author: 'Canadian Digital Service'

inputs:
  allow-failure:
    description: 'Allow the action to fail'
    required: false
    default: 'false'
  comment:
    description: 'Add comment with changes to the PR'
    required: false
    default: 'true'
  comment-delete:
    description: 'Delete previous comments made by the bot on the PR'
    required: false
    default: 'false'    
  comment-title:
    description: 'The title to give the PR comment'
    required: false
    default: 'Plan changes'    
  directory:
    description: 'Directory with the *.tf files to validate'
    required: false
    default: '.'    
  github-token:
    description: 'GitHub Token used to add comment to PR'
    required: false
    default: 'false'
  iam-role:
    description: 'IAM role to use with the terragrunt plan command'
    required: false
    default: ''    
  terraform-init:
    description: 'Custom Terraform init args'
    required: false
    default: ''     
  terragrunt:
    description: 'Use Terragrunt instead of Terraform'
    required: false
    default: 'false'  

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'layers'  
  color: 'purple'  
