name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup Node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with: 
          node-version: "20.7.0"

      - name: Setup NPM cache
        uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-npm-

      - name: Format, lint and test
        run: |
          npm ci
          npm run lint
          npm run format:check
          npm test

      - name: Test dist has been updated
        env:
          DIST_OLD: dist-old
          DIST: dist
        run: |
            cp -r $DIST $DIST_OLD
            npm run build
            diff -r $DIST $DIST_OLD || exit 1
          