name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with: 
          node-version: "20.7.0"

      - name: Setup NPM cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-npm-

      - name: Format, lint and test
        run: |
          npm ci
          npm run lint
          npm run format:check
          npm test

      - name: Test dist has been updated
        env:
          DIST_OLD: dist-old
          DIST: dist
        run: |
            cp -r $DIST $DIST_OLD
            npm run build
            diff -r $DIST $DIST_OLD || exit 1
          