name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with: 
          node-version: "20.7.0"

      - name: Setup NPM cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-npm-

      - name: Format, lint and test
        run: |
          npm ci
          npm run lint
          npm run format:check
          npm test

      - name: Test dist has been updated
        env:
          DIST_OLD: dist-old
          DIST: dist
        run: |
            cp -r $DIST $DIST_OLD
            npm run build
            diff -r $DIST $DIST_OLD || exit 1
          