name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with: 
          node-version: "20.7.0"

      - name: Setup NPM cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-npm-

      - name: Format, lint and test
        run: |
          npm ci
          npm run lint
          npm run format:check
          npm test

      - name: Test dist has been updated
        env:
          DIST_OLD: dist-old
          DIST: dist
        run: |
            cp -r $DIST $DIST_OLD
            npm run build
            diff -r $DIST $DIST_OLD || exit 1
          