name: Test action
on: pull_request

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - test: changes
            allow-failure: false
            skip-plan: false
          - test: no-changes
            allow-failure: false
            skip-plan: false
          - test: format-error
            allow-failure: true
            skip-plan: false
          - test: invalid
            allow-failure: true
            skip-plan: false
          - test: conftest-deny
            allow-failure: true
            skip-plan: false
          - test: skip-plan
            allow-failure: false
            skip-plan: true
          - test: truncate-plan
            allow-failure: false
            skip-plan: false            
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Test ${{ matrix.test }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: ./
        with:
          directory: test/${{ matrix.test }}
          allow-failure: ${{ matrix.allow-failure }}
          comment-title: Test ${{ matrix.test }}
          comment-delete: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-plan: ${{ matrix.skip-plan }}

  test-action-comments:
    needs: terraform-plan
    runs-on: ubuntu-latest
    steps:
      - name: Test action comments
        uses: actions/github-script@7dff1a87643417cf3b95bb10b29f4c4bc60d8ebd # tag=v6.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let isFailed = false;
            const testComments = [
              {
                exist: true,
                title: /Test changes/g,
                state: /`success`[^`]+`success`/g
              },{
                exist: true,
                title: /Test format-error/g,
                state: /`failed`[^`]+`success`/g
              },{
                exist: true,
                title: /Test invalid/g,
                state: /`failed`[^`]+`failed`/g
              },{
                exist: false,
                title: /Test no-changes/g,
                state: /./g
              },{
                exist: true,
                title: /Test conftest-deny/g,
                state: /FAIL/g
              },{
                exist: true,
                title: /Test skip-plan/g,
                state: /Terraform Format:\*\* `success`\n/gm
              },{
                exist: true,
                title: /Test truncate-plan/g,
                state: /plan has been truncated/gm
              }
            ];

            // Get the existing comments.
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
            });

            // Run through the tests
            let botComment;
            for(let test of testComments){
              botComment = comments.find(comment => comment.body.match(test.title) && comment.body.match(test.state));
              if((botComment && !test.exist) || (!botComment && test.exist)){
                console.log(`Failed '${test.title}'`);
                isFailed = true;
              }
            }

            if(isFailed){
              core.setFailed('PR comments did not match');
            }